### ISSUE TITLE
MusicPlayerService

### ISSUE THREAD

**Issue by hqu666** [hqu666/marasongs#14]
### クラス生成 
　MPSIntent = new Intent(MuList.this, MusicPlayerService.class);
　MuList.onCreate
　onClick　lp_ppPButton：プレイヤーの再生/停止ボタン

### 再生対象の受け取り
リストクリックでプレイヤー #3 にuriを送る
　send2Player(String pref_data_url ,boolean toPlaying)
　　resultLauncherでMaraSonActivity　を呼ぶ
 　　　＜　listClickで
　　　　　　全曲リストのMyConstants.v_titol
　　　　　　reqCode == MENU_infoKaisou
　　　　　　yobidashiMoto == veiwPlayer
 　　　＜　onClickで
　　　　　　rc_fbace :プレイヤーフィールド部の土台クリック

requestListTuika ; リクエストリスト作成
 back2Player( sousaRecordUrl); : リストからの戻り処理;プレイヤーにuriを送る

- ACTION_PLAYPAUSE
  - processTogglePlaybackRequest
    - 再生していない
      -  processPlayRequest();
    - 再生中
      -  processPauseRequest();
- ACTION_SKIP
  - processSkipRequest
    - playNextSong(mIndex++,true);
- ACTION_REWIND
  - processRewindRequest
    - playNextSong(mIndex--,true);

### 再生曲情報
- getDataInfo(String urlStr)　　urlからタイトルなどの情報読み出し
  - metadataBuilder に情報をセットして 
    - mediaSession.setMetadata(metadataBuilder.build()); 
- buildMediaMetadataCompat

ノティフィケーションプレイヤー #4
### MediaPlayer管理
- getMediaPlayer
  - MediaPlayer生成
  - 読み出し元は 
    - createMediaPlayerIfNeeded
    - playNextSong を追加
- playNextSong
  - ここでmPlayerにデータを読み込ませる
  - 読み出し元は 
    - processPlayRequest　で　mState == State.Stopped
      - onStartCommand　で　ACTION_PLAYPAUSE/ACTION_PLAY_READ/ACTION_PLAY/ACTION_REQUEST_STATE/ACTION_KEIZOKU/ACTION_UKETORI はprocessPlayRequestを経て
    - okuriMpdosi　で　frCount == 0 ||  mPlayer == null)
    - onCompletion　で　
    - onMusicRetrieverPrepared　で　mStartPlayingAfterRetrieve
    - onStartCommand　で　action.equals(ACTION_LISTSEL
  
 - processPlayRequest
   - Paused/Playのトグル処理
   - 遷移先は
     - mStateがPausedでconfigAndStartMediaPlayer
     - mStateがStoppedもしくは上記以外でplayNextSong(false)

 - mPlayer.start();があるのは
   - processRewindRequest() 再生ポジションが3秒未満の場合、前の曲に戻す
   - configAndStartMediaPlayer  指定された再生ポジションから再生を再開する
   - phoneCallEvent でTelephonyManager.CALL_STATE_IDLEの場合
   - onStartCommand　でaction.equals(ACTION_PLAY_READ)の場合
   - 
   - onAudioFocusChange 旧記載

**Comment by hqu666** [comment]
playNextSong: [MusicPlayerService]isOnlyPrepareはfalse,現在nowList[12896]jpmp;/storage/emulated/0/Music/サカナクション/834.194 [Disc 1]/1-01 忘れられないの.m4a[-1]/storage/emulated/0/Music/サカナクション/834.194 [Disc 1]/1-01 忘れられないの.m4a.0/482487[ms],dataFN=/storage/emulated/0/Music/サカナクション/834.194 [Disc 1]/1-01 忘れられないの.m4a,リスト中-1でjava.lang.NullPointerException: Attempt to invoke virtual method 'int com.hijiyam_koubou.marasongs.MusicPlaylist.getUserListMaxPlayOrder(int)' on a null object reference

**Comment by hqu666** [comment]
### 問題
-2023-02-20 23:47:30.321 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hijiyam_koubou.marasongs, PID: 8943
    android.app.RemoteServiceException$CannotPostForegroundServiceNotificationException: Bad notification for startForeground
        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1982)
        at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

- アルバムアート取得できず
- - 2023-02-15 23:13:45.243 E/getAlbumArtResId: [OrgUtil],albumId=1208293418336100926,retUri=content://media/external/audio/albumart/1208293418336100926,drawable=android.graphics.drawable.BitmapDrawable@2d2787dでjava.lang.NumberFormatException: For input string: "2d2787d"

**Comment by hqu666** [comment]
MyConstants.

**Comment by hqu666** [comment]
レシーバへ

**Comment by hqu666** [comment]
CursorWindow: Failed to read row 0, column 4294967295 from a window with 422 rows, 15 columns

readCalentList: [MusicPlayerService],getPageSize=4096件、でjava.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

**Comment by hqu666** [comment]
2022-09-03 00:07:21.434 E/lpNotificationMake: [MusicPlayerService]mState= Playing ,mcPosition= 00mS]KeyArtist =Jamiroquai,keyAlbum =High Times: Singles 1992-2006 [Bonus Track],keyTitle =Virtual Insanity,albumArt =null,dataFN =/storage/emulated/0/Music/John Mayer/Inside Wants Out/04 Neon.m4a[List_id=12936]練習-1[mIndex=6/9]>>mcPosition=0/0mS]でjava.lang.IllegalArgumentException: com.hijiyam_koubou.marasongs: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
